// src/langurage/en.js
// 定义英文语言包对象
export default {
  reward: {
    Rewards: "Rewards",
    Donate: "Donate",
    "Donate Balance": "Donate Balance",
    "Daily Cheak-in": "Daily Cheak-in",
    Day: "Day",
    Today: "Today",
    "Cheak in": "Cheak in",
    "Novice task": "Novice task",
    "Daily task": "Daily task",
    "Bind my account": "Bind my account",
    "Follow us on TikTok": "Follow us on TikTok",
    "Follow us on Youtube": "Follow us on Youtube",
    "Follow us on Facebook": "Follow us on Facebook",
    "Follow us on Instagram": "Follow us on Instagram",
    GO: "GO",
    Watch: "Watch",
    "Donate per episode": "Donate per episode",
    "Watch Ads": "Watch Ads",
    "Watch a whole series": "Watch a whole series",
    Ep: "Ep",
    "Come back tomorrow": "Come back tomorrow",
    Congratulations: "Congratulations!",
    "Successful Check": "Successful Check",
    ok: "OK",
    "Reward Rules": "Reward Rules",
    readme:
      "1. All interpretation rights of reward coins belongs to Dramabox.<br /> 2. You can only check-in once per day<br />3. lf you miss a check-in day, your check-in streak will be reset and counted from the first day.<br /> 4. Reward coins can only be used to unlock episodes. You can check the consumption records in your wallet.<br /> 5. Coins will be used first when unlocking episodes. If the amount is insufficient, reward coins will automatically be used.<br /> 6. Both the coins and the reward coins will never expire.<br /> 7. All tasks and sign-ins will be refreshed at 0 o'clock.",
    "Turn push notification": "Turn push notification",
  },
  leave: {
    Opinion: "Opinion",
    "Please Select Feedback Type": "Select",
    "Descript of Your Problem": "Describe your problem here",
    "Enter Your Email Address": "Enter Your Email Address",
    Submit: "Submit",
    "Feedback Type": "Feedback Type",
    Confirm: "Confirm",
    "Please select your feedback type": "Please select your feedback type",
    "The number of words in your problem description cannot be less than 10":
      "The number of words in your problem description cannot be less than 10",
    "Please enter your email": "Please enter your email",
    "Successfully submitted": "Successfully submitted",
    "Image size cannot exceed": "Image size cannot exceed",
    "Upload image": "Upload image",
    "Feedback List": "Feedback List",
    "No feedback history records found": "No feedback history records found",
    "Feedback Details": "Feedback Details",
    "Problem Type": "Problem Type",
    "Feedback Again": "Feedback Again",
    "Customer Reply": "Customer Service Reply",
    "Our Reply": "Did our response",
    "Did we solve your problem?": "resolve your problem?",
    "Continue Feedback": "Continue Feedback",
    Yes: "Yes",
    Replied: "Replied",
    Submitted: "Submitted",
    "Thank you for your feedback, we will reply in two working days, please be patient!":
      "Thank you for your feedback!<br>we will reply in two working days.<br>please be patient!",
    "Thank you for your feedback!": "Thank you for your feedback!",
    "No reply to any content": "No reply to any content",
    "Upload no more than 8 pictures": "Upload no more than 8 pictures",
    "Upload succeeded": "Upload succeeded",
  },
  common: {
    "This event is not related to Apple Inc":
      "This event is not related to Apple Inc.",
  },
};
