// src/langurage/ja.js
// 定义日语语言包对象
export default {
  reward: {
    Rewards: "ポイントイベント",
    Donate: "ポイント",
    "Donate Balance": "ポイント残高",
    "Daily Cheak-in": "毎日のチェックイン",
    Day: "日",
    Today: "本日",
    di: "第",
    tian: "日",
    "Cheak in": "チェックイン",
    "Novice task": "初心者任務",
    "Daily task": "デイリー任務",
    "Bind my account": "アカウントをバインドする",
    "Follow us on TikTok": "TikTok で私たちをフォローしてください",
    "Follow us on Youtube": "Youtube で私たちをフォローしてください",
    "Follow us on Facebook": "Facebook で私たちをフォローしてください",
    "Follow us on Instagram": "Instagram で私たちをフォローしてください",
    GO: "行く",
    Watch: "動画を見る",
    "Donate per episode": "ポイント 各広告",
    "Watch Ads": "広告を見る",
    "Watch a whole series": "一つの連続ドラマを全部見る",
    Ep: "Ep",
    "Come back tomorrow": "明日また来てください",
    Congratulations: "おめでとうございます！完了しました！",
    "Successful Check": "チェックイン成功",
    ok: "確認",
    "Reward Rules": "報酬ルール",
    readme:
      "1. イベントの最終解釈権は Guyan TV に属します。<br /> 2. ユーザーは毎日一度だけチェックインできます。<br /> 3. ユーザーが未ログインのためにチェックインが中断された場合、チェックインの進捗は 1 日目にリセットされます。<br /> 4. 報酬ゴールドはドラマのロック解除にのみ使用できます。履歴はウォレットで確認できます。<br /> 5. ゴールドはドラマのロック解除時に優先的に使用されます。金額が足りない場合は自動的に報酬ゴールドが使用されます。<br /> 6. ゴールドと報酬ゴールドの有効期限は無期限です。<br /> 7. すべてのタスクとチェックインは 0 時に更新されます。",
    "Turn push notification": "プッシュ通知をオンにする",
  },
  leave: {
    Opinion: "意見",
    "Please Select Feedback Type": "選択",
    "Descript of Your Problem": "あなたの問題の説明",
    "Enter Your Email Address": "あなたのメールアドレスを入力してください",
    Submit: "提出",
    "Feedback Type": "フィードバックの種類",
    Confirm: "確認",
    "Please select your feedback type":
      "あなたのフィードバックの種類を選択してください",
    "The number of words in your problem description cannot be less than 10":
      "問題の説明の文字数は 10 文字以上でなければなりません",
    "Please enter your email": "あなたのメールを入力してください",
    "Successfully submitted": "提出成功",
    "Image size cannot exceed": "画像サイズは〇〇を超えてはいけません",
    "Upload image": "画像をアップロードする",
    "Feedback List": "フィードバックリスト",
    "No feedback history records found":
      "フィードバックの履歴記録が見つかりません",
    "Feedback Details": "フィードバック詳細",
    "Problem Type": "問題の種類",
    "Feedback Again": "再度フィードバック",
    "Customer Reply": "顧客サービスからの返信",
    "Our Reply": "私たちからの返信",
    "Did we solve your problem?": "あなたの問題を解決しましたか？",
    "Continue Feedback": "フィードバックを続ける",
    Yes: "はい",
    Replied: "返信済み",
    Submitted: "提出済み",
    "Thank you for your feedback, we will reply in two working days, please be patient!":
      "お問い合わせいただき、誠にありがとうございます。<br>２営業日以内にまたご連絡いたしますので、<br>どうぞよろしくお願いいたします。",
    "Thank you for your feedback!":
      "フィードバックをいただきありがとうございます",
    "No reply to any content": "何も返事なし",
    "Upload no more than 8 pictures":
      "画像のアップロードは 8 枚を超えてはいけません",
    "Upload succeeded": "アップロード成功しました",
  },
};
