// src/langurage/vi.js
// 定义越南语言包对象
export default {
  reward: {
    Rewards: "Hoạt động tích điểm",
    Donate: "điểm tích lũy",
    "Donate Balance": "Số dư điểm tích lũy",
    "Daily Cheak-in": "Đăng ký hàng ngày",
    Day: "Ngày",
    Today: "Hnay",
    di: "Số",
    tian: "Ngày",
    "Cheak in": "Đăng ký",
    "Novice task": "Nhiệm vụ Newbie",
    "Daily task": "Nhiệm vụ hàng ngày",
    "Bind my account": "Gắn kết tài khoản",
    "Follow us on TikTok": "Theo dõi chúng tôi trên TikTok",
    "Follow us on Youtube": "Theo dõi chúng tôi trên YouTube",
    "Follow us on Facebook": "Theo dõi chúng tôi trên Facebook",
    "Follow us on Instagram": "Theo dõi chúng tôi trên Instagram",
    GO: "Đi tới",
    Watch: "Đi xem",
    "Donate per episode": "điểm tích lũy cho mỗi video",
    "Watch Ads": "Xem quảng cáo",
    "Watch a whole series": "Xem một bộ truyện dài hoàn chỉnh",
    Ep: "Ep",
    "Come back tomorrow": "Hãy quay lại ngày mai",
    Congratulations: "Chúc mừng đã hoàn thành!",
    "Successful Check": "Đăng ký thành côn",
    ok: "Xác nhận",
    "Reward Rules": "Thể lệ khen thưởng",
    readme:
      "1. Quyền giải thích cuối cùng của hoạt động thuộc về Guyan TV.<br /> 2. Người dùng chỉ có thể đăng ký một lần mỗi ngày.<br /> 3. Nếu người dùng bị gián đoạn việc đăng ký do chưa đăng nhập, tiến độ đăng ký sẽ được đặt lại về ngày đầu tiên.<br />4. Tiền vàng thưởng chỉ có thể được sử dụng để mở khóa các tập phim. Bạn có thể xem lịch sử trong ví của mình.<br /> 5. Khi mở khóa tập phim, tiền vàng sẽ được sử dụng trước. Nếu số tiền không đủ, tiền vàng thưởng sẽ được sử dụng tự động.<br /> 6. Thời hạn hiệu lực của tiền vàng và tiền vàng thưởng đều là vô thời hạn.<br /> 7. Tất cả nhiệm vụ và việc đăng ký sẽ được làm mới vào lúc 0 giờ.",
    "Turn push notification": "Bật thông báo đẩy",
  },
  leave: {
    Opinion: "Ý kiến",
    "Please Select Feedback Type": "Lựa chọn",
    "Descript of Your Problem": "Mô tả vấn đề của bạn",
    "Enter Your Email Address": "Nhập địa chỉ hộp thư của bạn",
    Submit: "Gửi",
    "Feedback Type": "Loại phản hồi",
    Confirm: "Xác nhận",
    "Please select your feedback type": "Vui lòng chọn loại phản hồi của bạn",
    "The number of words in your problem description cannot be less than 10":
      "Số từ mô tả câu hỏi không được thấp hơn 10 từ",
    "Please enter your email": "Vui lòng nhập Email của bạn",
    "Successfully submitted": "Gửi thành công",
    "Image size cannot exceed": "Kích thước ảnh không được vượt quá",
    "Upload image": "Tải lên hình ảnh",
    "Feedback List": "Danh sách phản hồi",
    "No feedback history records found":
      "Không tìm thấy bất kỳ lịch sử phản hồi nào",
    "Feedback Details": "Chi tiết phản hồi",
    "Problem Type": "Loại câu hỏi",
    "Feedback Again": "Phản hồi lại",
    "Customer Reply": "Trả lời của nhân viên hỗ trợ",
    "Our Reply": "Trả lời của chúng tôi",
    "Did we solve your problem?":
      "Bạn đã giải quyết được vấn đề của mình chưa?",
    "Continue Feedback": "Phản hồi tiếp tục",
    Yes: "Vâng",
    Replied: "Đã trả lời.",
    Submitted: "Phản hồi thành công.",
    "Thank you for your feedback, we will reply in two working days, please be patient!":
      "Cảm ơn phản hồi của bạn.<br> Chúng tôi sẽ trả lời trong hai ngày làm việc. <br>Xin hãy kiên nhẫn.",
    "Thank you for your feedback!": "Cảm ơn bạn đã phản hồi!",
    "No reply to any content": "Chưa trả lời.",
    "Upload no more than 8 pictures": "Tải lên không quá 8 ảnh",
    "Upload succeeded": "Tải lên thành công",
  },
};
