// src/langurage/zh.js
// 定义中文语言包对象
export default {
  reward: {
    Rewards: "积分活动",
    Donate: "积分",
    "Donate Balance": "积分余额",
    "Daily Cheak-in": "每日签到",
    Day: "天",
    Today: "今天",
    di: "第",
    tian: "天",
    "Cheak in": "签到",
    "Novice task": "新手任务",
    "Daily task": "每日任务",
    "Bind my account": "绑定账号",
    "Follow us on TikTok": "在抖音关注我们",
    "Follow us on Youtube": "在Youtube关注我们",
    "Follow us on Facebook": "在Facebook关注我们",
    "Follow us on Instagram": "在Instagram关注我们",
    GO: "前往",
    Watch: "观看视频",
    "Donate per episode": "积分 每条广告",
    "Watch Ads": "观看广告",
    "Watch a whole series": "看一整部连续剧",
    Ep: "Ep",
    "Come back tomorrow": "明天再来",
    Congratulations: "恭喜完成!",
    "Successful Check": "签到成功",
    ok: "确认",
    "Reward Rules": "奖励规则",
    readme:
      "1.活动最终解释权属于 Guyan TV。<br /> 2.用户每日只可签到一次。<br /> 3.如果用户因为未登录导致签到中断，签到进度将被重置回第一天。<br /> 4.奖励金币只可用来解锁剧集，您可以在钱包中查看历史记录。<br /> 5.金币在解锁剧集时会优先被使用，如果金额不够将会自动使用奖励金币。<br /> 6.金币和奖励金币的有效期均为无限期。<br /> 7.所有任务和签到会在0点刷新。",
    "Turn push notification": "开启推送通知",
  },
  leave: {
    Opinion: "意见",
    "Please Select Feedback Type": "选择",
    "Descript of Your Problem": "描述您的问题",
    "Enter Your Email Address": "输入您的邮箱地址",
    Submit: "提交",
    "Feedback Type": "反馈类型",
    Confirm: "确认",
    "Please select your feedback type": "请选择您的反馈类型",
    "The number of words in your problem description cannot be less than 10":
      "描述问题字数不能低于10个字",
    "Please enter your email": "请输入您的邮箱地址",
    "Successfully submitted": "提交成功",
    "Image size cannot exceed": "图片尺寸不能超过",
    "Upload image": "上传图片",
    "Feedback List": "反馈列表",
    "No feedback history records found": "找不到任何反馈历史记录",
    "Feedback Details": "反馈详情",
    "Problem Type": "问题类型",
    "Feedback Again": "再次反馈",
    "Customer Reply": "客服回复",
    "Our Reply": "我们的回复",
    "Did we solve your problem?": "解决了您的问题吗？",
    "Continue Feedback": "继续反馈",
    Yes: "是的",
    Replied: "已回复",
    Submitted: "反馈成功",
    "Thank you for your feedback, we will reply in two working days, please be patient!":
      "感谢您的反馈！<br>我们将会在两个工作日进行回复。<br>请耐心等待！",
    "Thank you for your feedback!": "感谢您的反馈！",
    "No reply to any content": "未回复任何内容",
    "Upload no more than 8 pictures": "上传图片不超过8张",
    "Upload succeeded": "上传成功",
  },
  common: {
    "This event is not related to Apple Inc": "本活动与苹果的无关",
  },
};
