// src/langurage/zh_hk.js
// 定义中文繁体语言包对象
export default {
  reward: {
    Rewards: "積分活動",
    Donate: "積分",
    "Donate Balance": "積分余額",
    "Daily Cheak-in": "每日签到",
    Day: "天",
    Today: "今天",
    di: "第",
    tian: "天",
    "Cheak in": "簽到",
    "Novice task": "新手任務",
    "Daily task": "每日任務",
    "Bind my account": "綁定賬號",
    "Follow us on TikTok": "在抖音關注我們",
    "Follow us on Youtube": "在Youtube關注我們",
    "Follow us on Facebook": "在Facebook關注我們",
    "Follow us on Instagram": "在Instagram關注我們",
    GO: "前往",
    Watch: "觀看視頻",
    "Donate per episode": "每條廣告積分",
    "Watch Ads": "觀看廣告",
    "Watch a whole series": "看一整部連續劇",
    Ep: "Ep",
    "Come back tomorrow": "明天再來",
    Congratulations: "恭喜完成!",
    "Successful Check": "簽到成功",
    ok: "確認",
    "Reward Rules": "獎勵規則",
    readme:
      "1.活動最終解釋權屬于 Guyan TV。<br /> 2.用戶每日只可簽到壹次。<br /> 3.如果用戶因爲未登錄導致簽到中斷，簽到進度將被重置回第壹天。<br /> 4.獎勵金幣只可用來解鎖劇集，您可以在錢包中查看曆史記錄。<br /> 5.金幣在解鎖劇集時會優先被使用，如果金額不夠將會自動使用獎勵金幣。<br /> 6.金幣和獎勵金幣的有效期均爲無限期。<br /> 7.所有任務和簽到會在0點刷新。",
    "Turn push notification": "開啟推送通知",
  },
  leave: {
    Opinion: "意見",
    "Please Select Feedback Type": "選擇",
    "Descript of Your Problem": "描述您的問題",
    "Enter Your Email Address": "輸入您的郵箱地址",
    Submit: "提交",
    "Feedback Type": "反饋類型",
    Confirm: "確認",
    "Please select your feedback type": "請選擇您的反饋類型",
    "The number of words in your problem description cannot be less than 10":
      "描述問題字數不能低於10個字",
    "Please enter your email": "請輸入您的郵件地址",
    "Successfully submitted": "提交成功",
    "Image size cannot exceed": "圖片尺寸不能超過",
    "Upload image": "上傳圖片",
    "Feedback List": "反饋列表",
    "No feedback history records found": "找不到任何反饋歷史記錄",
    "Feedback Details": "反饋詳情",
    "Problem Type": "問題類型",
    "Feedback Again": "再次反饋",
    "Customer Reply": "客服回復",
    "Our Reply": "我們的回復",
    "Did we solve your problem?": "解決了您的問題嗎？",
    "Continue Feedback": "繼續反饋",
    Yes: "是的",
    Replied: "已回覆",
    Submitted: "反饋成功",
    "Thank you for your feedback, we will reply in two working days, please be patient!":
      "感謝您的反饋！<br>我們將會在兩個工作日進行回覆。<br>請耐心等待！",
    "Thank you for your feedback!": "感謝您的反饋！",
    "No reply to any content": "未回復任何內容",
    "Upload no more than 8 pictures": "上傳圖片不超過8張",
    "Upload succeeded": "上傳成功",
  },
};
